### PR TITLE
Fix lines with mixed indentation (tabs AND spaces)

### PR DESCRIPTION
**Pull request by DennisKehrig**
Hey David,

I did not want to pester you with another issue and was kind of eager to try it myself, so here it is: a patch to fix lines with mixed indentation, correctly taking into account that a tab indents as much as a space followed by a tab, etc.

Enjoy!

Dennis

### CODE REVIEW

**Comment by davidderaedt** [comment]
Sounds great

**Comment by DennisKehrig** [comment]
Thanks for merging! Deleted my fork again. Your extension makes me eager to create one that shows whitespace somehow...

**Comment by davidderaedt** [comment]
Exactly! That was on my todo list too ;) I don't know if CodeMirror exposes some mechanism which would allow this kind of white space visualization...

David Deraedt

**Comment by DennisKehrig** [comment]
Check it out: https://github.com/DennisKehrig/brackets-show-indentations

It's an evil hack, I would say. But it's rather solid - at least in the scenarios I tested it with.

**Comment by davidderaedt** [comment]
Nice, I'll try that !

**Comment by DennisKehrig** [comment]
Switched to a totally different approach. I hope I now lack any reason to tinker with it some more :)

**Comment by davidderaedt** [comment]
Just tried it, this is great, thanks!

**Pull request merged**
